### ISSUE TITLE
Add baconts to http://definitelytyped.org/

### ISSUE THREAD

**Issue by cocodrino** [bodil/baconts#1]
Hi..can you add this project to http://definitelytyped.org/ ??...I'm getting troubles using it likes a node module (all kind of warnings and errors in completition)...would be nice a simple approach as the provided for 

http://definitelytyped.org/

thanks!!

**Comment by bodil** [comment]
Sorry, I'm not really maintaining this and I couldn't maintain a copy on DefinitelyTyped. You're welcome to add it on my behalf if you like (running `npm run compile` in this repo should get you a usable `.d.ts` file).
